<?xml version="1.0" encoding="UTF-8"?>
<!-- maxkey-starter-otp 模块的 Maven 配置。 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dromara.maxkey</groupId>
        <artifactId>maxkey-starter</artifactId>
        <version>4.2.0</version>

    </parent>
    <artifactId>maxkey-starter-otp</artifactId>
    <name>maxkey-starter-otp</name>
    <description>maxkey-starter-otp</description>

    <dependencies>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-entity</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-persistence</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-support</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.mail</groupId>
            <artifactId>jakarta.mail-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
