<?xml version="1.0" encoding="UTF-8"?>
<!-- maxkey-synchronizer 模块的 Maven 配置。 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dromara.maxkey</groupId>
        <artifactId>maxkey-synchronizers</artifactId>
        <version>4.2.0</version>

    </parent>
    <artifactId>maxkey-synchronizer-activedirectory</artifactId>
    <name>maxkey-synchronizer-activedirectory</name>
    <description>maxkey-synchronizer</description>

    <dependencies>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-ldap</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-entity</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-persistence</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-synchronizer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
    </dependencies>

</project>
