<?xml version="1.0" encoding="UTF-8"?>
<!-- Starter 模块聚合 POM。 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dromara.maxkey</groupId>
        <artifactId>MaxKey</artifactId>
        <version>4.2.0</version>
    </parent>
    <artifactId>maxkey-starter</artifactId>
    <packaging>pom</packaging>
    <name>maxkey-starter</name>
    <modules>
        <module>maxkey-starter-captcha</module>
        <module>maxkey-starter-ip2location</module>
        <module>maxkey-starter-otp</module>
        <module>maxkey-starter-passkey</module>
        <module>maxkey-starter-sms</module>
        <module>maxkey-starter-social</module>
        <module>maxkey-starter-web</module>
        <module>maxkey-starter-web-static</module>
    </modules>
</project>
