<?xml version="1.0" encoding="UTF-8"?>
<!-- maxkey-web-api-scim 模块的 Maven 配置。 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dromara.maxkey</groupId>
        <artifactId>maxkey-web-apis</artifactId>
        <version>4.2.0</version>

    </parent>
    <artifactId>maxkey-web-api-scim</artifactId>
    <name>maxkey-web-api-scim</name>
    <description>maxkey-web-api-scim</description>

    <dependencies>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-entity</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.maxkey</groupId>
            <artifactId>maxkey-persistence</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.mybatis-jpa-extra</groupId>
            <artifactId>mybatis-jpa-extra</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
