maxkey:
  app:
    issuer: CN=ConSec,CN=COM,CN=SH
  auth:
    jwt:
      expires: ${SERVER_EXPIRES:600}
      issuer: ${maxkey.server.uri}
      refresh:
        expires: ${SERVER_REFRESH_EXPIRES:1800}
        secret: 7heM-14BtxjyKPuH3ITIm7q2-ps5MuBirWCsrrdbzzSAOuSPrbQYiaJ54AeA0uH2XdkYy3hHAkTFIsieGkyqxOJZ_dQzrCbaYISH9rhUZAKYx8tUY0wkE4ArOC6LqHDJarR6UIcMsARakK9U4dhoOPO1cj74XytemI-w6ACYfzRUn_Rn4e-CQMcnD1C56oNEukwalf06xVgXl41h6K8IBEzLVod58y_VfvFn-NGWpNG0fy_Qxng6dg8Dgva2DobvzMN2eejHGLGB-x809MvC4zbG7CKNVlcrzMYDt2Gt2sOVDrt2l9YqJNfgaLFjrOEVw5cuXemGkX1MvHj6TAsbLg
      secret: 7heM-14BtxjyKPuH3ITIm7q2-ps5MuBirWCsrrdbzzSAOuSPrbQYiaJ54AeA0uH2XdkYy3hHAkTFIsieGkyqxOJZ_dQzrCbaYISH9rhUZAKYx8tUY0wkE4ArOC6LqHDJarR6UIcMsARakK9U4dhoOPO1cj74XytemI-w6ACYfzRUn_Rn4e-CQMcnD1C56oNEukwalf06xVgXl41h6K8IBEzLVod58y_VfvFn-NGWpNG0fy_Qxng6dg8Dgva2DobvzMN2eejHGLGB-x809MvC4zbG7CKNVlcrzMYDt2Gt2sOVDrt2l9YqJNfgaLFjrOEVw5cuXemGkX1MvHj6TAsbLg
  crypto:
    password:
      encoder: bcrypt
  ipaddress:
    whitelist: false
  notices:
    visible: false
  oidc:
    metadata:
      authorizationEndpoint: ${maxkey.server.authz.uri}/authz/oauth/v20/authorize
      issuer: ${maxkey.server.authz.uri}
      tokenEndpoint: ${maxkey.server.authz.uri}/authz/oauth/v20/token
      userinfoEndpoint: ${maxkey.server.authz.uri}/api/connect/userinfo
  otp:
    policy:
      digits: 6
      domain: ${maxkey.server.domain}
      issuer: ${OTP_POLICY_ISSUER:MaxKey}
      period: 30
      type: totp
  saml:
    v20:
      assertion:
        validity:
          time:
            ins:
              seconds: 90
      idp:
        issuer: ${maxkey.server.authz.uri}/saml
        issuing:
          entity:
            id: maxkey.top
        keystore: classpath:config/samlServerKeystore.jks
        keystore.password: maxkey
        receiver:
          endpoint: https://sso.maxkey.top/
      issue:
        instant:
          check:
            clock:
              skew:
                in:
                  seconds: 90
            validity:
              time:
                in:
                  seconds: 300
      max:
        parser:
          pool:
            size: 2
      metadata:
        company: MaxKeyTop
        contactType: technical
        emailAddress: support@maxsso.net
        givenName: maxkey
        orgDisplayName: MaxKeyTop
        orgName: MaxKeyTop
        orgURL: https://www.maxkey.top
        surName: maxkey
        telephoneNumber: 4008981111
      replay:
        cache:
          life:
            in:
              millis: 14400000
      sp:
        issuing:
          entity:
            id: client.maxkey.org
        keystore: classpath:config/samlClientKeystore.jks
        keystore.password: maxkey
        keystore.private.key.password: maxkey
  login:
    basic:
      enable: false
    captcha: ${LOGIN_CAPTCHA:true}
    captcha.type: ${LOGIN_CAPTCHA:TEXT}
    httpheader:
      enable: false
      headername: header-user
    jwt: ${LOGIN_JWT:false}
    jwt.issuer: ${LOGIN_JWT_ISSUER:${maxkey.server.authz.uri}}
    kerberos: false
    kerberos.default.crypto: 846KZSzYq56M6d5o
    kerberos.default.fulluserdomain: MAXKEY.ORG
    kerberos.default.redirecturi: http://sso.maxkey.top/kerberos/authn/
    kerberos.default.userdomain: MAXKEY
    mfa: ${LOGIN_MFA_ENABLED:true}
    mfa.type: ${LOGIN_MFA_TYPE:TimeBasedOtpAuthn}
    passkey:
      enabled: true
      relying-party:
        allowed-origins: http://localhost
        id: localhost
        name: MaxKey
    remeberme: ${LOGIN_REMEBERME:true}
    remeberme.validity: 0
    socialsignon: ${LOGIN_SOCIAL_ENABLED:true}
    wsfederation: false
    wsfederation.identifier: http://adfs.maxkey.top/adfs/services/trust
  server:
    authz:
      uri: ${maxkey.server.name}:${server.port}${server.servlet.context-path}
    basedomain: ${SERVER_DOMAIN:maxkey.top}
    default:
      uri: ${maxkey.server.uri}/appList
    domain: sso.${maxkey.server.basedomain}
    frontend:
      uri: http://localhost:8527/maxkey
    mgt:
      uri: ${maxkey.server.name}:9527/maxkey-mgt/login
    name: ${maxkey.server.scheme}://${maxkey.server.domain}
    persistence: ${SERVER_PERSISTENCE:0}
    scheme: http
    uri: ${maxkey.server.name}:${server.port}${server.servlet.context-path}
  job:
    cron:
      enable: true
      schedule: 0 0 0/1 * * ?
  swagger:
    description: MaxKey单点登录认证系统API文档
    title: MaxKey单点登录认证系统API文档
    version: ${application.formatted-version}
